FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD spring-boot1.jar /opt/spring-boot1/
EXPOSE 8080
WORKDIR /opt/spring-boot1/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "spring-boot1.jar"]
